# Generated by Django 6.0.2 on 2026-02-06 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=20, null=True, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Sangli', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('dealer', 'Dealer'), ('reseller', 'Reseller')], default='individual', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(default='Sangli', max_length=100, verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Purchase Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Outstanding Balance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20, verbose_name='Preferred Payment Method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount Paid'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchases',
            field=models.IntegerField(default=0, verbose_name='Total Purchases'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')], verbose_name='Phone Number'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_c_name_f018e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city'], name='customers_c_city_571324_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'),
        ),
    ]
