# Generated by Django 6.0.2 on 2026-02-05 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['name'], 'verbose_name': 'Business Profile', 'verbose_name_plural': 'Business Profiles'},
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_holder',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='closing_time',
            field=models.TimeField(default='18:00:00', verbose_name='Closing Time'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='currency',
            field=models.CharField(default='₹', max_length=10, verbose_name='Currency Symbol'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='currency_name',
            field=models.CharField(default='Indian Rupee', max_length=50, verbose_name='Currency Name'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='footer_note',
            field=models.TextField(blank=True, null=True, verbose_name='Invoice/Quote Footer Note'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=10, verbose_name='Invoice Prefix'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='invoice_start_number',
            field=models.PositiveIntegerField(default=1001, verbose_name='Starting Invoice Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='opening_time',
            field=models.TimeField(default='09:00:00', verbose_name='Opening Time'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='payment_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='proforma_prefix',
            field=models.CharField(default='PRO', max_length=10, verbose_name='Proforma Prefix'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='purchase_order_prefix',
            field=models.CharField(default='PO', max_length=10, verbose_name='Purchase Order Prefix'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='quotation_prefix',
            field=models.CharField(default='QUO', max_length=10, verbose_name='Quotation Prefix'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='quotation_start_number',
            field=models.PositiveIntegerField(default=1001, verbose_name='Starting Quotation Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='receipt_prefix',
            field=models.CharField(default='REC', max_length=10, verbose_name='Receipt Prefix'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline/Slogan'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Default Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='working_days',
            field=models.CharField(default='Monday to Saturday', max_length=100, verbose_name='Working Days'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100, verbose_name='State'),
        ),
    ]
